/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:5af26e76-0126-4a84-98cd-7ff1d6081aad",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_p65uzYlaF",
    "aws_user_pools_web_client_id": "sui2flnqca907vc559i04u5vs",
    "oauth": {}
};


export default awsmobile;
