/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:7c7f42f8-839e-459e-b3bf-63366ffe32fe",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_TdqIlIhMB",
    "aws_user_pools_web_client_id": "1g30jjge1pnbui5b9no7v6vkc8",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "blogTable-dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
